feat: divine grenade wod fix
elysiera/canary pull request #668
Opened 2023-09-01 06:02 UTC by jarrodpjohnston

2023-09-01 18:27 UTC, jarrodpjohnston commented on src/creatures/players/wheel/player_wheel.cpp
> +int32_t PlayerWheel::checkDivineGrenade(const Creature* target) const {
should we use this in game.cpp to drive the grade dmg?  (see checkExecutionersThrow)

2023-09-01 21:00 UTC, luan requested changes

2023-09-01 21:00 UTC, luan commented on data-otservbr-global/scripts/spells/attack/divine_grenade.lua
> +	if not creature and creature:isPlayer() then
this is not equivalent to what it was before, and I think is incorrect now:

`not creature` and `creature:isPlayer()` would cause a `nil` creature to run `creature:isPlayer()` which would in turn be invalid.
```suggestion
	if not (creature and creature:isPlayer()) then
```

2023-09-01 21:00 UTC, luan commented on data-otservbr-global/scripts/spells/attack/divine_grenade.lua
> +
```suggestion
```

2023-09-01 21:00 UTC, luan commented on src/creatures/players/wheel/player_wheel.cpp
> +int32_t PlayerWheel::checkDivineGrenade(const Creature* target) const {
yes i think so

2023-09-02 02:48 UTC, jarrodpjohnston commented on data-otservbr-global/scripts/spells/attack/divine_grenade.lua
> +	if not creature and creature:isPlayer() then
updated it to the same logic as Exec Throw

2023-09-02 19:45 UTC, luan approved these changes

2023-09-02 20:08 UTC, merged